"""patria

Revision ID: 5253ec53a653
Revises: 
Create Date: 2015-01-18 20:04:01.962503

"""

# revision identifiers, used by Alembic.
revision = '5253ec53a653'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('last_tweet_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=200, convert_unicode=True), nullable=True),
    sa.Column('screen_name', sa.String(length=200, convert_unicode=True), nullable=True),
    sa.Column('description', sa.String(convert_unicode=True), nullable=True),
    sa.Column('url', sa.String(convert_unicode=True), nullable=True),
    sa.Column('location', sa.String(convert_unicode=True), nullable=True),
    sa.Column('lang', sa.String(length=50, convert_unicode=True), nullable=True),
    sa.Column('default_profile', sa.Boolean(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('geo_enabled', sa.Boolean(), nullable=True),
    sa.Column('favourites_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('friends_count', sa.Integer(), nullable=True),
    sa.Column('listed_count', sa.Integer(), nullable=True),
    sa.Column('statuses_count', sa.Integer(), nullable=True),
    sa.Column('json', sa.String(convert_unicode=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screen_name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('tweet_id', sa.String(convert_unicode=True), nullable=True),
    sa.Column('text', sa.String(length=150, convert_unicode=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('retweet_count', sa.Integer(), nullable=True),
    sa.Column('favorite_count', sa.Integer(), nullable=True),
    sa.Column('lang', sa.String(length=50, convert_unicode=True), nullable=True),
    sa.Column('source', sa.String(convert_unicode=True), nullable=True),
    sa.Column('json', sa.String(convert_unicode=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweet_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    op.drop_table('users')
    ### end Alembic commands ###
